### PR TITLE
msm_vidc devices need to be in camera group

### PR DESCRIPTION
**Pull request by sebanc**
Tested and working

### CODE REVIEW

**Comment by DevSwift** [comment]
What this patch will fix?

**Comment by sebanc** [comment]
This patch allows the cameraserver to access the msm_vidc devices without granting them 666 permissions. After this patch and Zaclimon's one (github.com/aosp-msm8960/android_hardware_qcom_media/commit/e3671e5e1e917583a11761c3e99d94a8e7f13194) the hardware video encoding seems to work fine in 1080p on my build.

Please disregard it if it is not helping.

Thanks for all your work.

**Comment by DevSwift** [comment]
I just want to know what this change so chill ;) it looks like this patch looks good

**Comment by sebanc** [comment]
Sorry I did not want to seem angry/rude (english is not my native language). It is my first time trying to contribute so i am just not confident.

**Pull request merged**
